### PR TITLE
migration for the next version of date-fns

### PR DESCRIPTION
**Pull request by mkg0**
I migrated the plugin for the next pre-release version. Also, you can publish it with `next` version like `date-fns`.

I didn't replace any version info about it. It would be good to add a note for v1 version and create a new branch named `v1` for keeping v1 in further.

### CODE REVIEW

**Comment by mkg0** [comment]
I published a temporary package through my pr named `babel-plugin-date-fns-next`:

```
yarn add babel-plugin-date-fns-next
```

**Comment by renchap** [comment]
Now that date-fns 2.0 is released, this should be updated (maybe) and merged.

**Comment by renchap** [comment]
Also this plugin may in fact no longer be useful as `date-fns` 2 supports tree-shaking if you use a bundler like Webpack/Parcel/rollup/…

**Comment by dteirney** [comment]
This plugin is still useful (and necessary) for people that are using bundler that doesn't yet support tree shaking, yes there are still some.

**Comment by existentialism** [comment]
@mkg0 sorry for the extreme delay, thanks so much! Merged as https://github.com/date-fns/babel-plugin-date-fns/commit/c479a38d0905b0de893929da79c3e09c1c5e2649

**Pull request closed without merging**
